---
- name: Verify
  hosts: all
  become: true
  tasks:

    - name: Import variables
      include_vars:
        file: "../../group_vars/all.yml"

        
    - name: Check if nextcloud container is running
      community.docker.docker_container_info:
        name: nextcloud
      register: nextcloud_result

    - name: Check if nextcloud-mysql container is running
      community.docker.docker_container_info:
        name: nextcloud-mysql
      register: mysql_result

    - name: Check if redis container is running
      community.docker.docker_container_info:
        name: Redis
      register: redis_result

    - name: Verify nextcloud container version
      ansible.builtin.fail:
        msg: "Nextcloud container version does not match expected version: {{ version }}"
      when: nextcloud_result.container.Config.Image.split(':')[-1] != version

    - name: Verify mysql container version
      ansible.builtin.fail:
        msg: "MySQL container version does not match expected version: {{ mysql_version }}"
      when: mysql_result.container.Config.Image.split(':')[-1] != mysql_version

    - name: Verify redis container version
      ansible.builtin.fail:
        msg: "Redis container version does not match expected version: {{ redis_version }}"
      when: redis_result.container.Config.Image.split(':')[-1] != redis_version

    - name: Debug nextcloud container info
      ansible.builtin.debug:
        var: nextcloud_result.container

    - name: Debug mysql container info
      ansible.builtin.debug:
        var: mysql_result.container

    - name: Debug redis container info
      ansible.builtin.debug:
        var: redis_result.container

