---
- name: docker run
  shell: docker compose up -d
  args:
    chdir: "/opt/nextcloud"
  register: docker_run_result
  failed_when: docker_run_result.rc != 0
  changed_when: docker_run_result.rc == 0
  ignore_errors: no

- name: Debug docker run result
  debug:
    var: docker_run_result
  when: docker_run_result.rc != 0


- name: docker stop nextcloud
  command: docker compose down
  args:
    chdir: "/opt/nextcloud"
  register: docker_run_result
  failed_when: docker_run_result.rc == 0
  changed_when: docker_run_result.rc != 0
  ignore_errors: no

- name: Debug docker run result
  debug:
    var: docker_run_result
  when: docker_run_result.rc == 0
