---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure /tmp/.ansible/tmp directory exists
      ansible.builtin.file:
        path: /tmp/.ansible/tmp
        state: directory
        mode: '0755'

  roles:
    - deploy


