---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: cisagov/docker-debian12-ansible:latest
    command: ""
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - converge
    - verify
