---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: localhost/debian12:test
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - converge
    - verify
